# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Modelo3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(693, 528)
        MainWindow.setMinimumSize(QtCore.QSize(693, 0))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Titulo1 = QtWidgets.QLabel(self.centralwidget)
        self.Titulo1.setGeometry(QtCore.QRect(200, 70, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Permanent Marker")
        self.Titulo1.setFont(font)
        self.Titulo1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 0);")
        self.Titulo1.setObjectName("Titulo1")
        self.fondoVe = QtWidgets.QLabel(self.centralwidget)
        self.fondoVe.setGeometry(QtCore.QRect(0, 70, 501, 41))
        self.fondoVe.setAutoFillBackground(False)
        self.fondoVe.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.fondoVe.setText("")
        self.fondoVe.setObjectName("fondoVe")
        self.fondegris = QtWidgets.QLabel(self.centralwidget)
        self.fondegris.setGeometry(QtCore.QRect(0, 160, 451, 31))
        self.fondegris.setAutoFillBackground(False)
        self.fondegris.setStyleSheet("background-color: rgb(59, 59, 59);")
        self.fondegris.setText("")
        self.fondegris.setObjectName("fondegris")
        self.Titulo2 = QtWidgets.QLabel(self.centralwidget)
        self.Titulo2.setGeometry(QtCore.QRect(220, 160, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        self.Titulo2.setFont(font)
        self.Titulo2.setStyleSheet("background-color: rgb(59, 59, 59);")
        self.Titulo2.setObjectName("Titulo2")
        self.Sexocomb = QtWidgets.QComboBox(self.centralwidget)
        self.Sexocomb.setGeometry(QtCore.QRect(50, 220, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.Sexocomb.setFont(font)
        self.Sexocomb.setStyleSheet("border-color: rgb(59, 59, 59);")
        self.Sexocomb.setObjectName("Sexocomb")
        self.Sexocomb.addItem("")
        self.Sexocomb.addItem("")
        self.Sexocomb.addItem("")
        self.Edadcomb = QtWidgets.QComboBox(self.centralwidget)
        self.Edadcomb.setGeometry(QtCore.QRect(160, 220, 69, 22))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(10)
        self.Edadcomb.setFont(font)
        self.Edadcomb.setStyleSheet("border-color: rgb(59, 59, 59);")
        self.Edadcomb.setObjectName("Edadcomb")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb.addItem("")
        self.Edadcomb_2 = QtWidgets.QComboBox(self.centralwidget)
        self.Edadcomb_2.setGeometry(QtCore.QRect(260, 220, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(10)
        self.Edadcomb_2.setFont(font)
        self.Edadcomb_2.setStyleSheet("border-color: rgb(59, 59, 59);")
        self.Edadcomb_2.setObjectName("Edadcomb_2")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_2.addItem("")
        self.Edadcomb_3 = QtWidgets.QComboBox(self.centralwidget)
        self.Edadcomb_3.setGeometry(QtCore.QRect(370, 220, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(10)
        self.Edadcomb_3.setFont(font)
        self.Edadcomb_3.setStyleSheet("border-color: rgb(59, 59, 59);")
        self.Edadcomb_3.setObjectName("Edadcomb_3")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.Edadcomb_3.addItem("")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(500, 220, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("border-color: rgb(59, 59, 59);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.Titulo3 = QtWidgets.QLabel(self.centralwidget)
        self.Titulo3.setGeometry(QtCore.QRect(480, 190, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        self.Titulo3.setFont(font)
        self.Titulo3.setStyleSheet("")
        self.Titulo3.setObjectName("Titulo3")
        self.Resultado1 = QtWidgets.QLabel(self.centralwidget)
        self.Resultado1.setGeometry(QtCore.QRect(220, 350, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.Resultado1.setFont(font)
        self.Resultado1.setText("")
        self.Resultado1.setObjectName("Resultado1")
        self.CalcularBo = QtWidgets.QPushButton(self.centralwidget)
        self.CalcularBo.setGeometry(QtCore.QRect(300, 270, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(10)
        font.setItalic(False)
        self.CalcularBo.setFont(font)
        self.CalcularBo.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);")
        self.CalcularBo.setObjectName("CalcularBo")
        self.Resultado2 = QtWidgets.QLabel(self.centralwidget)
        self.Resultado2.setGeometry(QtCore.QRect(390, 350, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        self.Resultado2.setFont(font)
        self.Resultado2.setText("")
        self.Resultado2.setObjectName("Resultado2")
        self.Resultado1_2 = QtWidgets.QLabel(self.centralwidget)
        self.Resultado1_2.setGeometry(QtCore.QRect(220, 410, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.Resultado1_2.setFont(font)
        self.Resultado1_2.setText("")
        self.Resultado1_2.setObjectName("Resultado1_2")
        self.Resultado2_2 = QtWidgets.QLabel(self.centralwidget)
        self.Resultado2_2.setGeometry(QtCore.QRect(390, 410, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        self.Resultado2_2.setFont(font)
        self.Resultado2_2.setText("")
        self.Resultado2_2.setObjectName("Resultado2_2")
        self.Resultado1_3 = QtWidgets.QLabel(self.centralwidget)
        self.Resultado1_3.setGeometry(QtCore.QRect(220, 470, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.Resultado1_3.setFont(font)
        self.Resultado1_3.setText("")
        self.Resultado1_3.setObjectName("Resultado1_3")
        self.Resultado2_3 = QtWidgets.QLabel(self.centralwidget)
        self.Resultado2_3.setGeometry(QtCore.QRect(390, 470, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        self.Resultado2_3.setFont(font)
        self.Resultado2_3.setText("")
        self.Resultado2_3.setObjectName("Resultado2_3")
        self.Titulo3_2 = QtWidgets.QLabel(self.centralwidget)
        self.Titulo3_2.setGeometry(QtCore.QRect(20, 350, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        self.Titulo3_2.setFont(font)
        self.Titulo3_2.setStyleSheet("")
        self.Titulo3_2.setObjectName("Titulo3_2")
        self.Titulo3_3 = QtWidgets.QLabel(self.centralwidget)
        self.Titulo3_3.setGeometry(QtCore.QRect(20, 410, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        self.Titulo3_3.setFont(font)
        self.Titulo3_3.setStyleSheet("")
        self.Titulo3_3.setObjectName("Titulo3_3")
        self.Titulo3_4 = QtWidgets.QLabel(self.centralwidget)
        self.Titulo3_4.setGeometry(QtCore.QRect(20, 470, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        self.Titulo3_4.setFont(font)
        self.Titulo3_4.setStyleSheet("")
        self.Titulo3_4.setObjectName("Titulo3_4")
        self.Edad = QtWidgets.QTextEdit(self.centralwidget)
        self.Edad.setGeometry(QtCore.QRect(160, 260, 81, 21))
        self.Edad.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Edad.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Edad.setObjectName("Edad")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(160, 290, 81, 21))
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setObjectName("textEdit_2")
        self.fondoVe.raise_()
        self.Titulo1.raise_()
        self.fondegris.raise_()
        self.Titulo2.raise_()
        self.Sexocomb.raise_()
        self.Edadcomb.raise_()
        self.Edadcomb_2.raise_()
        self.Edadcomb_3.raise_()
        self.comboBox.raise_()
        self.Titulo3.raise_()
        self.Resultado1.raise_()
        self.CalcularBo.raise_()
        self.Resultado2.raise_()
        self.Resultado1_2.raise_()
        self.Resultado2_2.raise_()
        self.Resultado1_3.raise_()
        self.Resultado2_3.raise_()
        self.Titulo3_2.raise_()
        self.Titulo3_3.raise_()
        self.Titulo3_4.raise_()
        self.Edad.raise_()
        self.textEdit_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Titulo1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffffff;\">Salud y Ejercicio</span></p></body></html>"))
        self.Titulo2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-style:italic; color:#ffffff;\">Introduce tus datos</span></p></body></html>"))
        self.Sexocomb.setItemText(0, _translate("MainWindow", "Sexo"))
        self.Sexocomb.setItemText(1, _translate("MainWindow", "Masculino"))
        self.Sexocomb.setItemText(2, _translate("MainWindow", "Femenino"))
        self.Edadcomb.setItemText(0, _translate("MainWindow", "Edad"))
        self.Edadcomb.setItemText(1, _translate("MainWindow", "1"))
        self.Edadcomb.setItemText(2, _translate("MainWindow", "2"))
        self.Edadcomb.setItemText(3, _translate("MainWindow", "3"))
        self.Edadcomb.setItemText(4, _translate("MainWindow", "4"))
        self.Edadcomb.setItemText(5, _translate("MainWindow", "5"))
        self.Edadcomb.setItemText(6, _translate("MainWindow", "6"))
        self.Edadcomb.setItemText(7, _translate("MainWindow", "7"))
        self.Edadcomb.setItemText(8, _translate("MainWindow", "8"))
        self.Edadcomb.setItemText(9, _translate("MainWindow", "9"))
        self.Edadcomb.setItemText(10, _translate("MainWindow", "10"))
        self.Edadcomb.setItemText(11, _translate("MainWindow", "11"))
        self.Edadcomb.setItemText(12, _translate("MainWindow", "12"))
        self.Edadcomb.setItemText(13, _translate("MainWindow", "13"))
        self.Edadcomb.setItemText(14, _translate("MainWindow", "14"))
        self.Edadcomb.setItemText(15, _translate("MainWindow", "15"))
        self.Edadcomb.setItemText(16, _translate("MainWindow", "16"))
        self.Edadcomb.setItemText(17, _translate("MainWindow", "17"))
        self.Edadcomb.setItemText(18, _translate("MainWindow", "18"))
        self.Edadcomb.setItemText(19, _translate("MainWindow", "19"))
        self.Edadcomb.setItemText(20, _translate("MainWindow", "20"))
        self.Edadcomb.setItemText(21, _translate("MainWindow", "21"))
        self.Edadcomb.setItemText(22, _translate("MainWindow", "22"))
        self.Edadcomb.setItemText(23, _translate("MainWindow", "23"))
        self.Edadcomb.setItemText(24, _translate("MainWindow", "24"))
        self.Edadcomb.setItemText(25, _translate("MainWindow", "25"))
        self.Edadcomb.setItemText(26, _translate("MainWindow", "26"))
        self.Edadcomb.setItemText(27, _translate("MainWindow", "27"))
        self.Edadcomb.setItemText(28, _translate("MainWindow", "28"))
        self.Edadcomb.setItemText(29, _translate("MainWindow", "29"))
        self.Edadcomb.setItemText(30, _translate("MainWindow", "30"))
        self.Edadcomb.setItemText(31, _translate("MainWindow", "31"))
        self.Edadcomb.setItemText(32, _translate("MainWindow", "32"))
        self.Edadcomb.setItemText(33, _translate("MainWindow", "33"))
        self.Edadcomb.setItemText(34, _translate("MainWindow", "34"))
        self.Edadcomb.setItemText(35, _translate("MainWindow", "35"))
        self.Edadcomb.setItemText(36, _translate("MainWindow", "36"))
        self.Edadcomb.setItemText(37, _translate("MainWindow", "37"))
        self.Edadcomb.setItemText(38, _translate("MainWindow", "38"))
        self.Edadcomb.setItemText(39, _translate("MainWindow", "39"))
        self.Edadcomb.setItemText(40, _translate("MainWindow", "40"))
        self.Edadcomb.setItemText(41, _translate("MainWindow", "41"))
        self.Edadcomb.setItemText(42, _translate("MainWindow", "42"))
        self.Edadcomb.setItemText(43, _translate("MainWindow", "43"))
        self.Edadcomb.setItemText(44, _translate("MainWindow", "44"))
        self.Edadcomb.setItemText(45, _translate("MainWindow", "45"))
        self.Edadcomb.setItemText(46, _translate("MainWindow", "46"))
        self.Edadcomb.setItemText(47, _translate("MainWindow", "47"))
        self.Edadcomb.setItemText(48, _translate("MainWindow", "48"))
        self.Edadcomb.setItemText(49, _translate("MainWindow", "49"))
        self.Edadcomb.setItemText(50, _translate("MainWindow", "50"))
        self.Edadcomb.setItemText(51, _translate("MainWindow", "51"))
        self.Edadcomb.setItemText(52, _translate("MainWindow", "52"))
        self.Edadcomb.setItemText(53, _translate("MainWindow", "53"))
        self.Edadcomb.setItemText(54, _translate("MainWindow", "54"))
        self.Edadcomb.setItemText(55, _translate("MainWindow", "55"))
        self.Edadcomb.setItemText(56, _translate("MainWindow", "56"))
        self.Edadcomb.setItemText(57, _translate("MainWindow", "57"))
        self.Edadcomb.setItemText(58, _translate("MainWindow", "58"))
        self.Edadcomb.setItemText(59, _translate("MainWindow", "59"))
        self.Edadcomb.setItemText(60, _translate("MainWindow", "60"))
        self.Edadcomb.setItemText(61, _translate("MainWindow", "61"))
        self.Edadcomb.setItemText(62, _translate("MainWindow", "62"))
        self.Edadcomb.setItemText(63, _translate("MainWindow", "63"))
        self.Edadcomb.setItemText(64, _translate("MainWindow", "64"))
        self.Edadcomb.setItemText(65, _translate("MainWindow", "65"))
        self.Edadcomb.setItemText(66, _translate("MainWindow", "66"))
        self.Edadcomb.setItemText(67, _translate("MainWindow", "67"))
        self.Edadcomb.setItemText(68, _translate("MainWindow", "68"))
        self.Edadcomb.setItemText(69, _translate("MainWindow", "69"))
        self.Edadcomb.setItemText(70, _translate("MainWindow", "70"))
        self.Edadcomb.setItemText(71, _translate("MainWindow", "71"))
        self.Edadcomb.setItemText(72, _translate("MainWindow", "72"))
        self.Edadcomb.setItemText(73, _translate("MainWindow", "73"))
        self.Edadcomb.setItemText(74, _translate("MainWindow", "74"))
        self.Edadcomb.setItemText(75, _translate("MainWindow", "75"))
        self.Edadcomb.setItemText(76, _translate("MainWindow", "76"))
        self.Edadcomb.setItemText(77, _translate("MainWindow", "77"))
        self.Edadcomb.setItemText(78, _translate("MainWindow", "78"))
        self.Edadcomb.setItemText(79, _translate("MainWindow", "79"))
        self.Edadcomb.setItemText(80, _translate("MainWindow", "80"))
        self.Edadcomb.setItemText(81, _translate("MainWindow", "81"))
        self.Edadcomb.setItemText(82, _translate("MainWindow", "82"))
        self.Edadcomb.setItemText(83, _translate("MainWindow", "83"))
        self.Edadcomb.setItemText(84, _translate("MainWindow", "84"))
        self.Edadcomb.setItemText(85, _translate("MainWindow", "85"))
        self.Edadcomb.setItemText(86, _translate("MainWindow", "86"))
        self.Edadcomb.setItemText(87, _translate("MainWindow", "87"))
        self.Edadcomb.setItemText(88, _translate("MainWindow", "88"))
        self.Edadcomb.setItemText(89, _translate("MainWindow", "89"))
        self.Edadcomb.setItemText(90, _translate("MainWindow", "90"))
        self.Edadcomb.setItemText(91, _translate("MainWindow", "91"))
        self.Edadcomb.setItemText(92, _translate("MainWindow", "92"))
        self.Edadcomb.setItemText(93, _translate("MainWindow", "93"))
        self.Edadcomb.setItemText(94, _translate("MainWindow", "94"))
        self.Edadcomb.setItemText(95, _translate("MainWindow", "95"))
        self.Edadcomb.setItemText(96, _translate("MainWindow", "96"))
        self.Edadcomb.setItemText(97, _translate("MainWindow", "97"))
        self.Edadcomb.setItemText(98, _translate("MainWindow", "98"))
        self.Edadcomb.setItemText(99, _translate("MainWindow", "99"))
        self.Edadcomb.setItemText(100, _translate("MainWindow", "100"))
        self.Edadcomb_2.setItemText(0, _translate("MainWindow", "Peso(Kg)"))
        self.Edadcomb_2.setItemText(1, _translate("MainWindow", "50"))
        self.Edadcomb_2.setItemText(2, _translate("MainWindow", "51"))
        self.Edadcomb_2.setItemText(3, _translate("MainWindow", "52"))
        self.Edadcomb_2.setItemText(4, _translate("MainWindow", "53"))
        self.Edadcomb_2.setItemText(5, _translate("MainWindow", "54"))
        self.Edadcomb_2.setItemText(6, _translate("MainWindow", "55"))
        self.Edadcomb_2.setItemText(7, _translate("MainWindow", "56"))
        self.Edadcomb_2.setItemText(8, _translate("MainWindow", "57"))
        self.Edadcomb_2.setItemText(9, _translate("MainWindow", "58"))
        self.Edadcomb_2.setItemText(10, _translate("MainWindow", "59"))
        self.Edadcomb_2.setItemText(11, _translate("MainWindow", "60"))
        self.Edadcomb_2.setItemText(12, _translate("MainWindow", "61"))
        self.Edadcomb_2.setItemText(13, _translate("MainWindow", "62"))
        self.Edadcomb_2.setItemText(14, _translate("MainWindow", "63"))
        self.Edadcomb_2.setItemText(15, _translate("MainWindow", "64"))
        self.Edadcomb_2.setItemText(16, _translate("MainWindow", "65"))
        self.Edadcomb_2.setItemText(17, _translate("MainWindow", "66"))
        self.Edadcomb_2.setItemText(18, _translate("MainWindow", "67"))
        self.Edadcomb_2.setItemText(19, _translate("MainWindow", "68"))
        self.Edadcomb_2.setItemText(20, _translate("MainWindow", "69"))
        self.Edadcomb_2.setItemText(21, _translate("MainWindow", "70"))
        self.Edadcomb_2.setItemText(22, _translate("MainWindow", "71"))
        self.Edadcomb_2.setItemText(23, _translate("MainWindow", "72"))
        self.Edadcomb_2.setItemText(24, _translate("MainWindow", "73"))
        self.Edadcomb_2.setItemText(25, _translate("MainWindow", "74"))
        self.Edadcomb_2.setItemText(26, _translate("MainWindow", "75"))
        self.Edadcomb_2.setItemText(27, _translate("MainWindow", "76"))
        self.Edadcomb_2.setItemText(28, _translate("MainWindow", "77"))
        self.Edadcomb_2.setItemText(29, _translate("MainWindow", "78"))
        self.Edadcomb_2.setItemText(30, _translate("MainWindow", "79"))
        self.Edadcomb_2.setItemText(31, _translate("MainWindow", "80"))
        self.Edadcomb_2.setItemText(32, _translate("MainWindow", "81"))
        self.Edadcomb_2.setItemText(33, _translate("MainWindow", "82"))
        self.Edadcomb_2.setItemText(34, _translate("MainWindow", "83"))
        self.Edadcomb_2.setItemText(35, _translate("MainWindow", "84"))
        self.Edadcomb_2.setItemText(36, _translate("MainWindow", "85"))
        self.Edadcomb_2.setItemText(37, _translate("MainWindow", "86"))
        self.Edadcomb_2.setItemText(38, _translate("MainWindow", "87"))
        self.Edadcomb_2.setItemText(39, _translate("MainWindow", "88"))
        self.Edadcomb_2.setItemText(40, _translate("MainWindow", "89"))
        self.Edadcomb_2.setItemText(41, _translate("MainWindow", "90"))
        self.Edadcomb_2.setItemText(42, _translate("MainWindow", "91"))
        self.Edadcomb_2.setItemText(43, _translate("MainWindow", "92"))
        self.Edadcomb_2.setItemText(44, _translate("MainWindow", "93"))
        self.Edadcomb_2.setItemText(45, _translate("MainWindow", "94"))
        self.Edadcomb_2.setItemText(46, _translate("MainWindow", "95"))
        self.Edadcomb_2.setItemText(47, _translate("MainWindow", "96"))
        self.Edadcomb_2.setItemText(48, _translate("MainWindow", "97"))
        self.Edadcomb_2.setItemText(49, _translate("MainWindow", "98"))
        self.Edadcomb_2.setItemText(50, _translate("MainWindow", "99"))
        self.Edadcomb_2.setItemText(51, _translate("MainWindow", "100"))
        self.Edadcomb_3.setItemText(0, _translate("MainWindow", "Altura(cm)"))
        self.Edadcomb_3.setItemText(1, _translate("MainWindow", "150"))
        self.Edadcomb_3.setItemText(2, _translate("MainWindow", "151"))
        self.Edadcomb_3.setItemText(3, _translate("MainWindow", "152"))
        self.Edadcomb_3.setItemText(4, _translate("MainWindow", "153"))
        self.Edadcomb_3.setItemText(5, _translate("MainWindow", "154"))
        self.Edadcomb_3.setItemText(6, _translate("MainWindow", "155"))
        self.Edadcomb_3.setItemText(7, _translate("MainWindow", "156"))
        self.Edadcomb_3.setItemText(8, _translate("MainWindow", "157"))
        self.Edadcomb_3.setItemText(9, _translate("MainWindow", "158"))
        self.Edadcomb_3.setItemText(10, _translate("MainWindow", "159"))
        self.Edadcomb_3.setItemText(11, _translate("MainWindow", "160"))
        self.Edadcomb_3.setItemText(12, _translate("MainWindow", "161"))
        self.Edadcomb_3.setItemText(13, _translate("MainWindow", "162"))
        self.Edadcomb_3.setItemText(14, _translate("MainWindow", "163"))
        self.Edadcomb_3.setItemText(15, _translate("MainWindow", "164"))
        self.Edadcomb_3.setItemText(16, _translate("MainWindow", "165"))
        self.Edadcomb_3.setItemText(17, _translate("MainWindow", "166"))
        self.Edadcomb_3.setItemText(18, _translate("MainWindow", "167"))
        self.Edadcomb_3.setItemText(19, _translate("MainWindow", "168"))
        self.Edadcomb_3.setItemText(20, _translate("MainWindow", "169"))
        self.Edadcomb_3.setItemText(21, _translate("MainWindow", "170"))
        self.Edadcomb_3.setItemText(22, _translate("MainWindow", "171"))
        self.Edadcomb_3.setItemText(23, _translate("MainWindow", "172"))
        self.Edadcomb_3.setItemText(24, _translate("MainWindow", "173"))
        self.Edadcomb_3.setItemText(25, _translate("MainWindow", "174"))
        self.Edadcomb_3.setItemText(26, _translate("MainWindow", "175"))
        self.Edadcomb_3.setItemText(27, _translate("MainWindow", "176"))
        self.Edadcomb_3.setItemText(28, _translate("MainWindow", "177"))
        self.Edadcomb_3.setItemText(29, _translate("MainWindow", "178"))
        self.Edadcomb_3.setItemText(30, _translate("MainWindow", "179"))
        self.Edadcomb_3.setItemText(31, _translate("MainWindow", "180"))
        self.Edadcomb_3.setItemText(32, _translate("MainWindow", "181"))
        self.Edadcomb_3.setItemText(33, _translate("MainWindow", "182"))
        self.Edadcomb_3.setItemText(34, _translate("MainWindow", "183"))
        self.Edadcomb_3.setItemText(35, _translate("MainWindow", "184"))
        self.Edadcomb_3.setItemText(36, _translate("MainWindow", "185"))
        self.Edadcomb_3.setItemText(37, _translate("MainWindow", "186"))
        self.Edadcomb_3.setItemText(38, _translate("MainWindow", "187"))
        self.Edadcomb_3.setItemText(39, _translate("MainWindow", "188"))
        self.Edadcomb_3.setItemText(40, _translate("MainWindow", "189"))
        self.Edadcomb_3.setItemText(41, _translate("MainWindow", "190"))
        self.Edadcomb_3.setItemText(42, _translate("MainWindow", "191"))
        self.Edadcomb_3.setItemText(43, _translate("MainWindow", "192"))
        self.Edadcomb_3.setItemText(44, _translate("MainWindow", "193"))
        self.Edadcomb_3.setItemText(45, _translate("MainWindow", "194"))
        self.Edadcomb_3.setItemText(46, _translate("MainWindow", "195"))
        self.Edadcomb_3.setItemText(47, _translate("MainWindow", "196"))
        self.Edadcomb_3.setItemText(48, _translate("MainWindow", "197"))
        self.Edadcomb_3.setItemText(49, _translate("MainWindow", "198"))
        self.Edadcomb_3.setItemText(50, _translate("MainWindow", "199"))
        self.Edadcomb_3.setItemText(51, _translate("MainWindow", "200"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Sedentario"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Actividad Ligera"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Actividad Moderada "))
        self.comboBox.setItemText(3, _translate("MainWindow", "Muy Activo"))
        self.Titulo3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-style:italic; color:#363636;\">Nivel de Actividad</span></p><p align=\"center\"><br/></p></body></html>"))
        self.CalcularBo.setText(_translate("MainWindow", "CALCULAR"))
        self.Titulo3_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-style:italic; color:#363636;\">Masa Corporal</span><br/></p></body></html>"))
        self.Titulo3_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-style:italic; color:#363636;\">Calorias Diarias</span></p></body></html>"))
        self.Titulo3_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-style:italic; color:#363636;\">Ejercicio</span></p></body></html>"))

import Lab3_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

